### ISSUE TITLE
Dates out of scope are rejected - but corrections not accepted

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#63] opened 2021-02-24 14:15 UTC
When adding activities that gets dates outside the project dates, the system refuses them. (Reasonable)
It then also refuses any updates within scope - and will not save the updates. 

![image](https://user-images.githubusercontent.com/78147093/109012805-b3ef6900-76b2-11eb-8796-f6b5e3c1eee8.png)

This is the University of Dodoma project /17 
David has since deleted the activities to be able to update.

**Comment by PRindby** [comment] 2021-02-24 14:22
Could this also lead to a breakdown if for some reason a project closes earlier than planned?

**Comment by pavelsokolov** [comment] 2021-02-25 13:04
@PRindby could you elaborate a bit? how does it refuse all updates? it just refuses to proceed, all the input data are still there, and you can edit the mentioned dates and click 'update' again. Also, it has nothing to do with the project start/end, but only with activity start/end itself.

i will then need a complete use case.

**Comment by PRindby** [comment] 2021-02-25 14:58
Thing is that even after updating the dates to be within the scope the system says that they are outside of the scope and will not update. So the only way to get the update through is to delete the activity and re-enter it within the scope. 

The system does not recognise that it has been updated to be within the project date scope (unless I overlooked David not really chosing a correct date - I will try myself to see if I can recreate it).

**Comment by PRindby** [comment] 2021-02-25 15:01
Nope, can't recreate it. Maybe it complains even though it is corrected? 

![image](https://user-images.githubusercontent.com/78147093/109172169-c3d67e00-7782-11eb-9a72-370cb446a5ba.png)

**Comment by PRindby** [comment] 2021-02-25 15:02
I got the above one and then just updated anyway... Will see if David can recreate it.

**Comment by PRindby** [comment] 2021-02-25 15:36
It _could_ be that error messages keeps showing even after they are no longer valid.
The system constanlty complains that there is no description even when there is for example.

**Comment by pavelsokolov** [comment] 2021-02-25 16:37
> I got the above one and then just updated anyway... Will see if David can recreate it.

It's just a confirmation, we can remove that check you want. Then I will leave this until we have a confirmed test case showing the error :)

**Comment by pavelsokolov** [comment] 2021-04-15 10:27
Closing this issue since it was fixed (dates check was incorrect, now fixed)

**Closed by pavelsokolov** 2021-04-15 10:27 UTC
